### ISSUE TITLE
Check 404 status code

### ISSUE THREAD

**Issue by stevenvachon** [Urucas/broken-links#3]
Why compare to a 404 document when you can check the response code?

**Comment by vrunoa** [comment]
Hi @stevenvachon, this package was built, initially, for internal usage. Most of our website are built on php Zend Framework. When an exception occurr or a file is missing it doesn't throw a 404, it just redirects to a custom 404 page, and I believe the response code is 200. This is why we compare the link source with the custom 404 page.

**Comment by vrunoa** [comment]
Althought it's a good idea to add the response code check before comparing with the source code. 

``` pseudocode
if( response.status == 404) {
    // perform error callback
}else if( response.status == 200) {
    if( page.source == 404.source) {
        // perform error callback
    }else {
        // perfork OK callback
    }
}

**Comment by stevenvachon** [comment]
Yes, please add that above code to the project source.

**Comment by vrunoa** [comment]
I'll add this.

**Comment by vrunoa** [comment]
Hey @stevenvachon just added statusCode validation. Before comparing the link source code with the 404 source code, checks the response status code. 

https://github.com/Urucas/broken-links/blob/master/index.js#L68
